### ISSUE TITLE
Dependency update required for Docker extension 

### ISSUE THREAD

**Issue by fiveisprime** [robertoachar/vscode-extension-pack#1]
Hi!

I just wanted to give you a heads up that the Docker extension has been migrated to a new publisher and, you'll need to update your dependency so it will install correctly.

Please update `"PeterJausovec.vscode-docker"` to `"ms-azuretools.vscode-docker"` to ensure the extension is installed correctly.

Thanks and sorry for the inconvenience.

**Comment by robertoachar** [comment]
Hey @fiveisprime,

I've removed this extension in an earlier version.

Thank you buddy.
